// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ginlayout/internal/config"
	"ginlayout/internal/handler"
	"ginlayout/internal/repository"
	"ginlayout/internal/router"
	"ginlayout/internal/service"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	configConfig := config.NewConfig()
	db := repository.NewDB(configConfig)
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	userRouter := router.NewUserRouter(userHandler)
	routerRouter := router.NewRouter(configConfig, userRouter)
	app := NewApp(routerRouter, configConfig)
	return app, func() {
	}, nil
}
